# kubernetes\apps\traefik\traefik-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
spec:
  selector:
    app: traefik
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
