version: "3"

vars:
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"

includes:
  ansible: .taskfiles/ansible/taskfile.yaml
  kubernetes: .taskfiles/kubernetes/taskfile.yaml

tasks:
  default:
    silent: true
    cmd: task -l
