---
- name: Pre tasks
  hosts: all
  pre_tasks:
    - name: Verify Ansible is version 2.11 or above.
      assert:
        that: "ansible_version.full is version_compare('2.11', '>=')"
        msg: >
          "Ansible is out of date. See here for more info."

- name: Prepare k3s nodes
  hosts: kubernetes  # Targets all hosts in the master and node groups
  gather_facts: true
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: prereq
      become: true
    - role: download
      become: true

- name: Setup k3s servers
  hosts: master
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: k3s_server
      become: true

- name: Setup k3s agents
  hosts: node
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: k3s_agent
      become: true

- name: Configure k3s cluster
  hosts: master
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: k3s_server_post
      become: true

- name: Storing kubeconfig in the playbook directory
  hosts: master
  environment: "{{ proxy_env | default({}) }}"
  tasks:
    - name: Copying kubeconfig from {{ hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname'] }}
      ansible.builtin.fetch:
        src: "{{ ansible_user_dir }}/.kube/config"
        dest: ./kubeconfig
        flat: true
      when: ansible_hostname == hostvars[groups[group_name_master | default('master')][0]]['ansible_hostname']
